name: Deploy to Heroku

on:
  push:
    branches:
      - module-2-exercise
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
          registry: registry.heroku.com

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release Docker image
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}