name: Deploy to Heroku

on:
  push:
    branches:
      - module-2-exercise

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Heroku Container Registry
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker Image
        run: docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .

      - name: Push to Heroku
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Release
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web --app $HEROKU_APP_NAME
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}